#!/usr/bin/python3
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2022  Marek Marczykowski-Górecki
#                               <marmarek@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

from __future__ import annotations

import os
import sys
from ipaddress import IPv4Address

FALLBACK_INTERNAL_DNS = ['10.139.1.1', '10.139.1.2']
FALLBACK_EXTERNAL_DNS = ['192.168.20.1']
QUBESDB_DNS_KEYS = ('/qubes-netvm-primary-dns', '/qubes-netvm-secondary-dns')


def parse_ipv4(value):
    try:
        return str(IPv4Address(value))
    except ValueError:
        return None


def get_internal_dns():
    try:
        import qubesdb
        qdb = qubesdb.QubesDB()
        found = [qdb.read(key) for key in QUBESDB_DNS_KEYS]
    except Exception as e:
        print(f'qubesdb unavailable, using fallback internal dns: {e}', file=sys.stderr)
        return FALLBACK_INTERNAL_DNS

    internal_dns = [ip for ip in (parse_ipv4(v.decode('ascii', 'ignore')) for v in found if v) if ip]
    return internal_dns or FALLBACK_INTERNAL_DNS


def get_external_dns(resolv_conf='/etc/resolv.conf'):
    external_dns = []
    try:
        with open(resolv_conf) as f:
            for line in f:
                fields = line.split()
                if len(fields) >= 2 and fields[0] == 'nameserver':
                    ip = parse_ipv4(fields[1])
                    if ip and not IPv4Address(ip).is_loopback:
                        external_dns.append(ip)
    except OSError as e:
        print(e, file=sys.stderr)

    return external_dns or FALLBACK_EXTERNAL_DNS


def generate_rules_list(internal_dns, external_dns):
    rules = [
        'table ip qubes {',
        'chain dnat-dns {',
        'type nat hook prerouting priority -150; policy accept;',
    ]

    for i, ns in enumerate(internal_dns):
        upstream = external_dns[i % len(external_dns)]
        rules.append(f'ip daddr {ns} udp dport 53 dnat to {upstream}')
        rules.append(f'ip daddr {ns} tcp dport 53 dnat to {upstream}')

    rules.append('}')
    rules.append('}')
    return rules


def apply_dnat_rules(rules):
    preamble = ['add table ip qubes', 'add chain ip qubes dnat-dns', 'delete chain ip qubes dnat-dns']
    os.execvp('nft', ['nft', '--', '\n'.join(preamble + rules)])


def install_firewall_rules():
    apply_dnat_rules(generate_rules_list(get_internal_dns(), get_external_dns()))


if __name__ == '__main__':
    install_firewall_rules()
