git:
  baseurl: https://github.com
  prefix: qubesos/qubes-
  branch: main

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.3
use-qubes-repo:
  version: 4.3
  testing: false
template-root-size: "30G"

templates:
  - kali-core:
      dist: bookworm
      flavor: kali-core
#      dist: trixie
#      options:
#        - no-recommends

#  - kali:
#      dist: trixie
#      flavor: kali
#      options:
#        - no-recommends

#  - kali-large:
#      dist: trixie
#      flavor: kali-large
#      options:
#        - no-recommends

#  - kali-everything:
#      dist: trixie
#      flavor: kali-everything
#      options:
#        - no-recommends


components:
  - builder-debian:
      packages: False
      maintainers:
        - 0064428F455451B3EBE78A7F063938BA42CFA724 #marek
        - 274E12AB03F2FE293765FC06DA0434BC706E1FCF #simon -> pretty this one is not valid but only need 1
  - template-kali:
      packages: False
      url: https://github.com/fepitre/qubes-template-kali
      branch: master
      maintainers:
        # fepitre's @qubes-os.org
        - 9FA64B92F95E706BF28E2CA6484010B5CDC576E2
        # fepitre's @invisiblethingslab.com
        - 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6

executor:
 type: docker
 options:
   image: "qubes-builder-debian:latest"

stages:
  - fetch
  - prep
  - build
  - sign:
     executor:
        type: local
#        options:
#     client: /usr/bin/gpg
#     key: 15B37E88AA6DD0AA6F47F9A86C3BA16540918FC3
